#!/bin/sh

LOCATION="$HOME/dots"

push_to_git(){
  # pushing to git  
  echo 'PUSHING'
  update-remote
  git add .
  git commit -m "backup $(date)"
  git push -u origin master

  cd $HOME/bin
  update-remote
  git add .
  git commit -m "backup $(date)"
  git push -u origin master
}

error(){
  echo $1
  exit
}

backup(){
  cd $LOCATION
  ls backups || mkdir backups

  # copying files
  cat $LOCATION/list.txt | while read line 
  do
    echo "backing up $line"
    rm -rf "backups/$(basename $line)"
    cp -r "$HOME/$line" "backups/$(basename $line)" || error "cannot copy $line"
  done

  push_to_git
}

retrive(){
  cd $LOCATION
  ls backups || error 'backups dir not found'

  # copying files
  cat $LOCATION/list.txt | while read line 
  do
    echo "retriving $line"
    cp -r "backups/$(basename $line)" "$HOME/$line" || echo "cannot copy $line"
  done
}

while getopts "r b a:" opt
do
  case "${opt}" in
    r) retrive;;
    b) backup;;
    a) echo ${OPTARG} >> $LOCATION/list.txt;;
    esac
done
